version: '3'

services:

  api:
    build:
      context: .
    hostname: api
    depends_on:
      - redis
    ports:
      - 1137:1137
    environment:
      - REDIS_URL=redis://redis:6379

  # database:
  #   image: postgres:alpine
  #   read_only: true
  #   tmpfs:
  #     - /tmp
  #     - /var/run/postgresql
  #   volumes:
  #     - db:/var/lib/postgresql/data
  #     - ./config/postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
  #
  redis:
    image: redis:alpine
    read_only: true
    volumes:
      - redis:/data
    user: redis

volumes:
  # db:
  redis:
  yarn:
