name: GitHub Pages

on: [push]
  # push:
    # branches:
    # - master

env:
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y libgl-dev libxi-dev python
    - run: npm install
    - run: npm run build
    - run: |
        git config --global user.name "Collin Schroeder"
        git config --global user.email "ubernaut@users.noreply.github.com"
        npm run push-gh-pages
